# SPDX-License-Identifier: GPL-3.0-only
#
# Copyright (C) 2021-2026  sirpdboy  <herboy2008@gmail.com> 
#
# This is free software, licensed under the Apache License, Version 2.0 .
#
include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-ddns-rs
PKG_VERSION:=1.6.8
PKG_RELEASE:=20260323

PKG_MAINTAINER:=sirpdboy  <herboy2008@gmail.com>
PKG_CONFIG_DEPENDS:=

LUCI_TITLE:=LuCI Support for Dynamic ddns-rs Client
LUCI_DEPENDS:=+ddns-rs
LUCI_PKGARCH:=all



include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
