use ddns_rs_core::config::Config;

/// Verify the config YAML format matches Go's yaml.v3 output (lowercase keys).
#[test]
fn test_go_config_compat() {
    // This file was generated by the Go implementation (see /tmp/go_full.yaml)
    let content = r#"dnsconf:
- name: cfg1
  ipv4:
    enable: true
    gettype: url
    url: https://ip.3322.net
    netinterface: ""
    cmd: ""
    domains:
    - www.example.com
    - test.example.com
  ipv6:
    enable: false
    gettype: ""
    url: ""
    netinterface: ""
    cmd: ""
    ipv6reg: ""
    domains: []
  dns:
    name: alidns
    id: LTAI5t
    secret: secretKey123
    extparam: ""
  ttl: "600"
  httpinterface: ""
user:
  username: admin
  password: $2a$10$hashed
webhook:
  webhookurl: ""
  webhookrequestbody: ""
  webhookheaders: ""
notallowwanaccess: false
lang: en
"#;

    let conf: Config = serde_yaml::from_str(content).unwrap();
    assert_eq!(conf.DnsConf.len(), 1);
    assert_eq!(conf.DnsConf[0].Name, "cfg1");
    assert_eq!(conf.DnsConf[0].Ipv4.Enable, true);
    assert_eq!(conf.DnsConf[0].Ipv4.GetType, "url");
    assert_eq!(conf.DnsConf[0].Ipv4.URL, "https://ip.3322.net");
    assert_eq!(conf.DnsConf[0].Ipv4.Domains, vec!["www.example.com", "test.example.com"]);
    assert_eq!(conf.DnsConf[0].DNS.Name, "alidns");
    assert_eq!(conf.DnsConf[0].DNS.ID, "LTAI5t");
    assert_eq!(conf.DnsConf[0].DNS.Secret, "secretKey123");
    assert_eq!(conf.DnsConf[0].TTL, "600");
    assert_eq!(conf.User.Username, "admin");
    assert_eq!(conf.User.Password, "$2a$10$hashed");
    assert_eq!(conf.Lang, "en");
    assert_eq!(conf.NotAllowWanAccess, false);

    // Serialize back and verify the keys stay lowercase
    let out = serde_yaml::to_string(&conf).unwrap();
    assert!(out.contains("dnsconf:"), "serialized should use lowercase key");
    assert!(out.contains("name: cfg1"), "got: {}", out);
    assert!(out.contains("enable: true"), "got: {}", out);
    assert!(out.contains("gettype: url"), "got: {}", out);
    assert!(out.contains("dns:"), "got: {}", out);
    assert!(out.contains("name: alidns"), "got: {}", out);
    assert!(out.contains("user:"), "got: {}", out);
    assert!(out.contains("username: admin"), "got: {}", out);
    assert!(!out.contains("DnsConf"), "should not contain uppercase keys");
    assert!(!out.contains("Ipv4"), "should not contain uppercase keys");
}

/// Simulate API responses with null arrays to verify serde handles them
/// like Go does (null -> empty slice, no error).
#[test]
fn test_null_vec_deserialization() {
    use ddns_rs_core::serde_util::deserialize_null_default_vec;

    // Verify the null-tolerant deserializer matches Go's behavior:
    // null -> empty Vec, missing -> empty Vec, array -> parsed.
    #[derive(serde::Deserialize)]
    struct SiteResp {
        #[serde(default, deserialize_with = "deserialize_null_default_vec")]
        sites: Vec<serde_json::Value>,
    }
    // explicit null
    let s: SiteResp = serde_json::from_str(r#"{"totalCount":0,"sites":null}"#).unwrap();
    assert!(s.sites.is_empty());
    // missing field
    let s: SiteResp = serde_json::from_str(r#"{"totalCount":0}"#).unwrap();
    assert!(s.sites.is_empty());
    // actual array
    let s: SiteResp = serde_json::from_str(r#"{"sites":[{"id":1},{"id":2}]}"#).unwrap();
    assert_eq!(s.sites.len(), 2);

    // Dnspod-style: records list
    #[derive(serde::Deserialize)]
    struct DnsPod {
        #[serde(default, deserialize_with = "deserialize_null_default_vec")]
        records: Vec<serde_json::Value>,
    }
    let d: DnsPod = serde_json::from_str(r#"{"records":null}"#).unwrap();
    assert!(d.records.is_empty());

    // Tencent-style RecordList
    #[derive(serde::Deserialize)]
    struct TcList {
        #[serde(default, deserialize_with = "deserialize_null_default_vec")]
        record_list: Vec<serde_json::Value>,
    }
    let t: TcList = serde_json::from_str(r#"{"RecordList":null}"#).unwrap();
    assert!(t.record_list.is_empty());

    // Huawei-style recordsets
    #[derive(serde::Deserialize)]
    struct Hw {
        #[serde(default, deserialize_with = "deserialize_null_default_vec")]
        recordsets: Vec<serde_json::Value>,
    }
    let h: Hw = serde_json::from_str(r#"{"recordsets":null}"#).unwrap();
    assert!(h.recordsets.is_empty());
}
