#!/bin/sh

uci set luci.languages.zh_cn='简体中文 (Simplified Chinese)'
uci commit luci
chmod 755 /usr/libexec/rpcd/luci.ddns-rs
chown root:www-data /usr/libexec/ddns-rs-call
chmod 750 /usr/libexec/ddns-rs-call
rm -f /tmp/luci-indexcache
/etc/init.d/rpcd restart
exit 0
